### ISSUE TITLE
replacing in appsettings json supposed to work?

### ISSUE THREAD

**Issue by rpanjwani** [qetza/vsts-replacetokens-task#204] opened 2021-03-26 23:34 UTC
I am trying to substitute a token in my appsettings.Staging.json file as below:

![image](https://user-images.githubusercontent.com/4108676/112702517-1d8fac80-8ed7-11eb-868c-43ca5915ffc0.png)

![image](https://user-images.githubusercontent.com/4108676/112702421-bbcf4280-8ed6-11eb-9eaa-80a38c842b07.png)

![image](https://user-images.githubusercontent.com/4108676/112702483-f6d17600-8ed6-11eb-9327-9bb883bf4454.png)

![image](https://user-images.githubusercontent.com/4108676/112702498-06e95580-8ed7-11eb-9786-6789093cce3a.png)

I've tried both "Release" and "Stage1" scope. But the value doesn't get replaced in the file:

**Comment by JohnL404** [comment] 2021-04-07 16:39
I'm suddenly seeing the same problem. None of my appSettings.*.json files are being transformed. Nothing else has changed in our deployment/configuration process in several weeks.

**Comment by qetza** [comment] 2021-04-07 19:17
Hi @rpanjwani, @JohnL404,
I'm going to take a look but there was no changes made to the task since mid February. Maybe it's a change on Azure Pipelines.
@JohnL404 are you also seeing the issue in releases (UI version) ?

**Comment by JohnL404** [comment] 2021-04-07 19:19
@qetza Yes, I am. I'm using the task in the release pipeline. Nothing changed on our end either so I lean toward it being an Azure issue. If I deploy from a release created a few days ago, it works, but a new release instance created today (again: no changes), and none of the transforms are applied. It's almost like it can't find the pipeline variables or something, maybe?

**Comment by qetza** [comment] 2021-04-07 19:48
@JohnL404, i cannot reproduce the issue my test release pipeline is replacing the tokens.
I'm using the windows hosted pool with agent version 2.184.2.
Could you share the debug logs of the task? (add variable `system.debug` with value `true`)

**Comment by JohnL404** [comment] 2021-04-07 20:15
@qetza I absolutely can, but while looking at the debug logs, I may have just stumbled upon the cause. No matter how far I go back, when I look at the Replace Tokens list of parameters, "Target files" is only set to "**/*.config". The recent debug logs do correctly indicate the task is _only_ processing any *.config files -- not the JSON files it had been updating earlier.

![image](https://user-images.githubusercontent.com/10673523/113926094-638b2100-97b1-11eb-9fd8-7ddf6668011b.png)

Even when I edit an existing release instance as far back as March 8th, that is the case when I look. According to the release edit history, that was not changed by anyone. If I re-run an earlier release pipeline instance, it correctly transforms the appSettings.*.json files and the output contains the non-tokenized values from our pipeline variables. However, when I edit that instance (and not the release pipeline definition itself), it doesn't look like it would affect any json files at all!

I apologize for wasting your time with this. When looking at the release change history and seeing nothing changed since long before this stopped working, I didn't take a closer look at the parameters of the task since a quick glance showed my other expected values. I don't know how the parameter was reset back to an apparent default of "**/*/config", but it works after I re-added the "**/appSettings.*.json" value to Target files.

**Comment by qetza** [comment] 2021-04-07 20:19
@JohnL404, no problem i'm glad the issue is solved on your side 😄

**Comment by qetza** [comment] 2021-12-12 06:49
Closing as the issue if fixed.

**Closed by qetza** 2021-12-12 06:49 UTC
