### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Skenja** [qetza/vsts-replacetokens-task#288] opened 2022-10-19 15:49 UTC
Running into an issue with V5 (also tested V4 with same results) task replacing tokens in a single large bundled and minified JS file (19MB) - Maximum call stack size exceeded. Bundled file is not under my control so it cannot be made smaller.

After disabling the minifying for the build process, the resulting file is 35MB, but the task passes for that file.

Running on a `windows-latest` agent, using Node 16.x. 

Would be happy to share the offending file privately for debugging purposes.

**Comment by qetza** [comment] 2022-11-22 07:16
Hi @Skenja,
Thanks for reporting the issue and sorry for the late reply.

You can send the file on my gmail dot com account: qetzac

I'll look at what is the issue and how to fix it

**Comment by Skenja** [comment] 2022-11-22 09:31
Hi @qetza, I sent them to your email. Thanks for responding, and please let me know if you need more input :)

**Comment by qetza** [comment] 2022-12-13 07:07
Hi @Skenja,
I'm getting some free time to work on issues, could you share with me your task parameters?

**Comment by Skenja** [comment] 2022-12-13 09:21
Done! Let me know if I can help!

**Comment by qetza** [comment] 2023-07-29 07:52
Hi @Skenja,
I'm finally getting some free time to work on this task and i'm having issue reproducing your issue.

Based on the files you sent me (.js and the task configuration) when trying to reproduce i don't have any call stack issue but the task finds no token to replace. The task configuration is using the pattern `#{ ... }#` but this pattern doesn't exists in the js files.

I could find the pattern `#{ ... }` with the variable names `key` and `\s*key\s*` but even when using this pattern i cannot reproduce the issue.

If you still have the issue could you share a debug log?

**Comment by qetza** [comment] 2024-03-10 19:01
I'm archiving the project and moving it to a new repository https://github.com/qetza/replacetokens-task

**Closed by qetza** 2024-03-10 19:01 UTC
Labels: bug
