### ISSUE TITLE
Getting Null Reference Exception with v3.7.0

### ISSUE THREAD

**Issue by quentinlami-e05043** [qetza/vsts-replacetokens-task#196] opened 2021-02-19 12:34 UTC
We are getting a null reference exceptions in all pipelines with running **v3.7.0**:

**##[error]Unable to process command '##vso[task.setvariable variable=tokenReplacedCount;isOutput=false;issecret=false;]15' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
##[error]Value cannot be null.**

**Comment by qetza** [comment] 2021-02-19 12:44
Hi @quentinlami-e05043,
Could you share some diagnostics logs as i cannot reproduce the issue. Which version of the agent are you using?

**Comment by quentinlami-e05043** [comment] 2021-02-19 13:15
> Hi @quentinlami-e05043,
> Could you share some diagnostics logs as i cannot reproduce the issue. Which version of the agent are you using?

See log file attached from version 3.7.0

[3_Replace tokens in .config.log](https://github.com/qetza/vsts-replacetokens-task/files/6010216/3_Replace.tokens.in.config.log)

**Comment by qetza** [comment] 2021-02-19 13:27
Thanks, could you tell me:
- are you using the task in YAML, build pipeline (UI) or release pipeline?
- which agent are you using, hosted or private?
- which version of the agent are you using?

**Comment by qetza** [comment] 2021-02-19 13:58
Hi @quentinlami-e05043,
I've published a patch version rollbacking the output variables, it seems that they may be incompatibility with some TFS/Azure DevOps versions.
I will add the feature in a new major version so that users will optin for the feature.

**Comment by SanjayKumar-V23126** [comment] 2021-02-19 14:42
are you using Azure DevOps or TFS and which version?
     Answer: TFS 2017 
are you using the task in YAML, build pipeline (UI) or release pipeline?
     Answer: Release Pipeline    
which agent are you using, hosted or private?
     Answer: Private 
which version of the agent are you using?
     Answer:  Agent.Version | 2.122.1

Here are the details if you want to reproduce the issue at your end. 
We will test the release pipeline again with the rolled back version - 3.7.1.

**Comment by qetza** [comment] 2021-02-19 15:55
Thanks @SanjayKumar-V23126, let me know if the issue is fixed with the latest version.

**Comment by SanjayKumar-V23126** [comment] 2021-02-19 16:00
@qetza - Yes, issue is fixed in the latest task version (3.7.1). 
Our Release pipelines are working fine now and thanks for quick turnaround.

**Closed** 2021-08-12 06:55 UTC
