### ISSUE TITLE
First character of secret value replaced by question mark

### ISSUE THREAD

**Issue by nemtajo** [qetza/vsts-replacetokens-task#184] opened 2021-01-18 10:23 UTC
Replace tokens task rule:
stunnel.tokenized.conf => stunnel.conf
Token prefix: #[
Token suffix: ]#

stunnel.tokenized.conf content:
[#[AquaRising-Stunnel-Configuration-Header-Pricing-Maker]#]
[#[AquaRising-Stunnel-Configuration-Header-Trading-Maker]#]
[#[AquaRising-Stunnel-Configuration-Header-Trading-BackOffice]#]

stunnel.conf content:
[Aqua-GoldiQuotes-Prices-Demo]
[Aqua-GoldiQuotes-Trades-Demo]
[?AquaDemo_BackOffice]

First two variables were correctly replaced, butthe third variable, had value 'xAquaDemo_BackOffice' in the key vault
![image](https://user-images.githubusercontent.com/7429763/104902725-fbc5f680-5976-11eb-8991-aa32b9a50765.png)

and the first character 'x' got replaced by '?'.

Please advise.

**Comment by nemtajo** [comment] 2021-01-18 11:22
Escaping x in secret value: '\xAquaDemo_BackOffice'
and setting custom escape character '\'
![image](https://user-images.githubusercontent.com/7429763/104909096-43508080-597f-11eb-9382-9d7e2066e4dc.png)
solved the problem for me.
But preferably, auto escaping shouldn't replace first character with question mark.

**Comment by qetza** [comment] 2021-02-05 07:15
Hi @nemtajo,
I will try to reproduce your issue, if i correctly understand you have linked your variable group to a key vault instance and the secret `AquaRising-Stunnel-Configuration-Header-Trading-BackOffice` which has a value of `xAquaDemo_BackOffice` is appearing with the value `?AquaDemo_BackOffice` in your file after token replacement?

**Comment by nemtajo** [comment] 2021-02-10 15:01
Hi @qetza , that is correct.

**Comment by qetza** [comment] 2021-02-18 11:07
Hi @nemtajo,
I cannot reproduce the issue, could you share your debug logs on the task so that i can see all configuration?

**Comment by davidbarrowsatasos** [comment] 2021-08-11 13:31
> Hi @qetza , I have a similar issue ... we're doing this in an Azure DevOps task:
> 
> * task: qetza.replacetokens.replacetokens-task.replacetokens@3
>   displayName: 'Replace tokens in Helm Chart'
>   inputs:
>   rootDirectory: '${{ parameters.environmentYamlPath }}'
>   targetFiles: ${{ parameters.environmentYamlFileName }}
>   tokenPrefix: '%'
>   tokenSuffix: '%'
>   escapeType: 'no escaping'
> 
> and one of the values is being transformed, and it has a GBP symbol in the string (it's a password); the symbol is "£" and it's being replaced by a question mark ("?"). Could you please give me any advice as to how I might fix this problem? Thank you! Dave

UPDATE:  actually never mind, I figured it out - if you add "encoding: 'utf-8' " that fixes it!  cheers

**Comment by qetza** [comment] 2021-12-12 06:47
Closing as the issue seems to be fixed.

**Closed by qetza** 2021-12-12 06:47 UTC
