### ISSUE TITLE
Variable Size

### ISSUE THREAD

**Issue by TimorKalerman** [qetza/vsts-replacetokens-task#97] opened 2019-02-03 08:17 UTC
I am getting "variable not found" when trying to replace a long text variable, for example:
"fe94180d0eae31d482c6c50d36ee76e06684b097978610f4151a8c61dc27134142ce7d94ca8785d19f54396bf117f19089e7c58ecc4eb17ec2bf832ade38738v"

**Comment by qetza** [comment] 2019-02-04 21:05
Hi,

That's strange as i'm using variables with long values and have no issues. Could you share your logs (add variable `system.debug` with `true` as a value) because the error message indicates that the variable with the name found is the token was not found not an issue on the value.

**Comment by TimorKalerman** [comment] 2019-02-05 08:51
From the logs:
[debug]SECRET_KEY_BASE=undefined
[warning]variable not found: SECRET_KEY_BASE
[debug]Processed: ##vso[task.issue type=warning;]variable not found: SECRET_KEY_BASE

But the variable is present in the Azure DevOps Library attached to the build:
![image](https://user-images.githubusercontent.com/23355662/52262027-e4c99d80-2933-11e9-9935-84691c235ae4.png)

Other Variables are replaced as expected.

**Comment by qetza** [comment] 2019-02-27 06:18
Hi,
Sorry for the late reply. I did a test with the value you provided in your first message and it worked.

Maybe the issue is not with the value but with the variable name, sometime when you copy/paste the variable in name you have none visible characters in the copy/paste.

Could you recreate a variable with the same name making sure you type it correctly?

**Comment by TimorKalerman** [comment] 2019-02-27 09:21
Hi,
Thanks for replying.
I think I found a strange behavior, it is not working only when I variable name begins with "SECRET_KEY".
Do you know anything about it? and does it works for you?

**Comment by qetza** [comment] 2019-02-27 16:30
Hi,
I think that the `SECRET_` prefix is used internally by Microsoft to prefix all variables marked as secret. So your variable may be confused for on of those. Try without `SECRET_`

**Comment by TimorKalerman** [comment] 2019-02-27 16:54
Yes probably this is the case.
Thank you very much for your help.

**Closed** 2019-03-07 13:01 UTC
