### ISSUE TITLE
Tokens not replacing

### ISSUE THREAD

**Issue by mrichman** [qetza/vsts-replacetokens-task#34] opened 2017-04-19 21:04 UTC
I have my variables set

![image](https://cloud.githubusercontent.com/assets/11228/25202118/35735db0-2522-11e7-98f4-71d90ce88808.png)

and my config file looks like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<parameters>
    <parameter name="AudienceUri" defaultValue="#{AudienceUri}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel/identityConfiguration/audienceUris/add/@value" />
    </parameter>
    <parameter name="StudentSTSThumbprint" defaultValue="#{StudentSTSThumbprint}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel/identityConfiguration/issuerNameRegistry/trustedIssuers/add[name='StudentSTS']/@thumbprint" />
    </parameter>
    <parameter name="Issuer" defaultValue="#{Issuer}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel.services/federationConfiguration/wsFederation/@issuer" />
    </parameter>
    <parameter name="Realm" defaultValue="#{Realm}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel.services/federationConfiguration/wsFederation/@realm" />
    </parameter>
    <parameter name="ApplicationName" defaultValue="#{ApplicationName}#">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/exceptionManagement/publisher[type='Microsoft.ApplicationBlocks.ExceptionManagement.DefaultPublisher']/@applicationName" />
    </parameter>
</parameters>
```

My log shows the task running:

```
2017-04-19T20:57:39.6522145Z ##[section]Starting: Replace tokens in parameters.xml
 
2017-04-19T20:57:41.5085788Z replacing tokens in: \\cltscmnfs1\Installs\Packages\StudentSTS\3.2.0.16\StudentSTS\parameters.xml
 
2017-04-19T20:57:41.6333764Z ##[section]Finishing: Replace tokens in parameters.xml
```

But when I view the XML file, nothing is replaced.

**Comment by qetza** [comment] 2017-04-20 08:31
Hi Mark,

Can you activate the debug logging by setting the variable `system.debug` at `true` and share the log? 

From what i see in your current log the file is found but no tokens are replaced so it could be an issue with the regex. What are the token prefix and suffix yu configured? (this will be logged in debug)

**Comment by mrichman** [comment] 2017-04-20 12:02
I activated system.debug=true, and here's the log:

![image](https://cloud.githubusercontent.com/assets/11228/25229712/5a7c3a00-259f-11e7-9546-5d0db33e010c.png)

My settings are as follows:

![image](https://cloud.githubusercontent.com/assets/11228/25229738/7395ce2a-259f-11e7-863a-3a5e38391ac0.png)

And this time it seemed to work, though I don't think I changed anything:

```
<?xml version="1.0" encoding="utf-8" ?>
<parameters>
    <parameter name="AudienceUri" defaultValue="https://portal.cmcscm.com:443/CMCPortal/">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel/identityConfiguration/audienceUris/add/@value" />
    </parameter>
    <parameter name="StudentSTSThumbprint" defaultValue="85DEC05BD2F4CEAC41F0D421061AF73FFC8681E8">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel/identityConfiguration/issuerNameRegistry/trustedIssuers/add[name='StudentSTS']/@thumbprint" />
    </parameter>
    <parameter name="Issuer" defaultValue="https://studentsts.cmcscm.com">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel.services/federationConfiguration/wsFederation/@issuer" />
    </parameter>
    <parameter name="Realm" defaultValue="https://portal.cmcscm.com/CMCPortal/">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/system.identityModel.services/federationConfiguration/wsFederation/@realm" />
    </parameter>
    <parameter name="ApplicationName" defaultValue=".NET Runtime">
        <parameterEntry kind="XmlFile" scope="\\Web\.config$" match="/configuration/exceptionManagement/publisher[type='Microsoft.ApplicationBlocks.ExceptionManagement.DefaultPublisher']/@applicationName" />
    </parameter>
</parameters>
```

**Comment by qetza** [comment] 2017-04-23 09:24
Hi Mark,
Could you give me some more information on your configuration:
- which version of VSTS/TFS (with update) are you using?
- which version of the task are you using?

In your log i see an issue, normally if you have tokens in your source file you should have a debug log for each token found but there is none in your log...

I've done a test with your file on VSTS with the latest version of the task (v2.0.1 of task, v2.0.2 of extension) and here is what i have:
![image](https://cloud.githubusercontent.com/assets/8191369/25312317/b14f8f5c-2816-11e7-83f9-b7dd3e9fb00a.png)

As you can see on the last lines i have one line for each found token with the name and variable value and replacement was done:
![image](https://cloud.githubusercontent.com/assets/8191369/25312351/5ae0f9e8-2817-11e7-9579-00a3afe1ac42.png)

**Comment by richardhauer** [comment] 2017-11-09 13:35
I'm trying to create a `build-info.txt` file by using a PowerShell script to write a file into the drop directory, then run your token replacer, then package and deploy the file.  The variables never get replaced, though the log indicates that the file was found.  I have the prefix and suffix set to `__` and am using the following system variables:
 - `__Release.ReleaseName__`
 - `__Build.BuildNumber__`
 - `__Release.EnvironmentName__`

Does the replacer only work with custom variables or should it work with the above as well?
Any ideas why mine wouldn't be working?

**Comment by qetza** [comment] 2017-11-09 17:36
Hi Richard,
Glad it works now.

Settings the variable to enable debug doesn't have any inpact as it only displays debug logs and there is no change in the process.

**Comment by richardhauer** [comment] 2017-11-09 21:40
Well sure. That was the only change we made between it not working across 10 attempts, and suddenly working.

So maybe there's something subtle happening





Richard Hauer
CTO
PING Works
L 13, 61 Lavender Street, Milsons Point NSW 2061
p: +61 2 9321 1551<tel:+61%202%209321%201551> | www.ping-works.com.au<https://www.ping-works.com.au>
d: +61 2 9321 1556<tel:+61%202%209321%201556> | m: +61 414 189 170<tel:+61%20414%20189%20170>
Download a vCard<https://ping-vcards.azurewebsites.net/api/GenerateVCF?name=richard.hauer>
-------- Original message --------

**Comment by qetza** [comment] 2017-11-23 21:07
As i cannot reproduce the issue and it's now working i'm closing the issue. Feel free to reopen if you have more data to reproduce.

**Closed by qetza** 2017-11-23 21:07 UTC
