### ISSUE TITLE
Tokens not replacing correctly

### ISSUE THREAD

**Issue by deMD** [qetza/vsts-replacetokens-task#118] opened 2019-10-03 08:37 UTC
I have a taks where I want to replace token in specific configuration files, however it does not seem to work correctly. All values is the config files get replaced with ##{variable}## like so
```xml
<setting key="CachedCDNRoot" value="##{Blob.CdnDomain}##" />
```

Here is my parameters.xml
[parameters.zip](https://github.com/qetza/vsts-replacetokens-task/files/3685126/parameters.zip)
And the SetParameters.xml
[CustomerPortal.Cms.SetParameters (4).zip](https://github.com/qetza/vsts-replacetokens-task/files/3685154/CustomerPortal.Cms.SetParameters.4.zip)

And the log as being put out by the task after enabling system.debug:
```
2019-10-03T08:29:29.2367057Z ##[debug]Evaluating condition for step: 'Replace tokens in **/*.SetParameters.xml'
2019-10-03T08:29:29.2367650Z ##[debug]Evaluating: succeeded()
2019-10-03T08:29:29.2367791Z ##[debug]Evaluating succeeded:
2019-10-03T08:29:29.2367992Z ##[debug]=> True
2019-10-03T08:29:29.2368205Z ##[debug]Result: True
2019-10-03T08:29:29.2368386Z ##[section]Starting: Replace tokens in **/*.SetParameters.xml
2019-10-03T08:29:29.2477759Z ==============================================================================
2019-10-03T08:29:29.2477874Z Task         : Replace Tokens
2019-10-03T08:29:29.2477936Z Description  : Replace tokens in files
2019-10-03T08:29:29.2478008Z Version      : 3.2.1
2019-10-03T08:29:29.2478065Z Author       : Guillaume Rouchon
2019-10-03T08:29:29.2478150Z Help         : v3.2.1 - [More Information](https://github.com/qetza/vsts-replacetokens-task#readme)
2019-10-03T08:29:29.2478232Z ==============================================================================
2019-10-03T08:29:29.4705879Z ##[debug]agent.TempDirectory=d:\a\_temp
2019-10-03T08:29:29.4737811Z ##[debug]loading inputs and endpoints
2019-10-03T08:29:29.4744489Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-10-03T08:29:29.4758178Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-10-03T08:29:29.4761790Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-10-03T08:29:29.4764312Z ##[debug]loading INPUT_ACTIONONMISSING
2019-10-03T08:29:29.4766189Z ##[debug]loading INPUT_EMPTYVALUE
2019-10-03T08:29:29.4767995Z ##[debug]loading INPUT_ENCODING
2019-10-03T08:29:29.4769692Z ##[debug]loading INPUT_ESCAPETYPE
2019-10-03T08:29:29.4771551Z ##[debug]loading INPUT_KEEPTOKEN
2019-10-03T08:29:29.4773305Z ##[debug]loading INPUT_ROOTDIRECTORY
2019-10-03T08:29:29.4774841Z ##[debug]loading INPUT_TARGETFILES
2019-10-03T08:29:29.4776644Z ##[debug]loading INPUT_TOKENPREFIX
2019-10-03T08:29:29.4778207Z ##[debug]loading INPUT_TOKENSUFFIX
2019-10-03T08:29:29.4779992Z ##[debug]loading INPUT_VERBOSITY
2019-10-03T08:29:29.4781567Z ##[debug]loading INPUT_WRITEBOM
2019-10-03T08:29:29.4792067Z ##[debug]loaded 14
2019-10-03T08:29:29.4812900Z ##[debug]Agent.ProxyUrl=undefined
2019-10-03T08:29:29.4815259Z ##[debug]Agent.CAInfo=undefined
2019-10-03T08:29:29.4815605Z ##[debug]Agent.ClientCert=undefined
2019-10-03T08:29:29.4815907Z ##[debug]Agent.SkipCertValidation=undefined
2019-10-03T08:29:29.5647503Z ##[debug]rootDirectory=d:\a\r1\a\
2019-10-03T08:29:29.5647880Z ##[debug]check path : d:\a\r1\a\
2019-10-03T08:29:29.5654520Z ##[debug]tokenPrefix=#{
2019-10-03T08:29:29.5661938Z ##[debug]tokenSuffix=}#
2019-10-03T08:29:29.5671799Z ##[debug]encoding=auto
2019-10-03T08:29:29.5675206Z ##[debug]keepToken=false
2019-10-03T08:29:29.5677183Z ##[debug]actionOnMissing=warn
2019-10-03T08:29:29.5678769Z ##[debug]writeBOM=true
2019-10-03T08:29:29.5680397Z ##[debug]emptyValue=(empty)
2019-10-03T08:29:29.5681931Z ##[debug]escapeType=none
2019-10-03T08:29:29.5683310Z ##[debug]escapeChar=null
2019-10-03T08:29:29.5684122Z ##[debug]charsToEscape=null
2019-10-03T08:29:29.5686249Z ##[debug]verbosity=normal
2019-10-03T08:29:29.5689314Z ##[debug]targetFiles=**/*.SetParameters.xml
2019-10-03T08:29:29.5693811Z ##[debug]pattern: #\{((?:(?!\}#).)*)\}#
2019-10-03T08:29:29.5699916Z ##[debug]defaultRoot: 'd:\a\r1\a\'
2019-10-03T08:29:29.5701248Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2019-10-03T08:29:29.5701523Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2019-10-03T08:29:29.5701707Z ##[debug]findOptions.followSymbolicLinks: 'true'
2019-10-03T08:29:29.5704582Z ##[debug]matchOptions.debug: 'false'
2019-10-03T08:29:29.5704875Z ##[debug]matchOptions.nobrace: 'true'
2019-10-03T08:29:29.5705066Z ##[debug]matchOptions.noglobstar: 'false'
2019-10-03T08:29:29.5705395Z ##[debug]matchOptions.dot: 'true'
2019-10-03T08:29:29.5705755Z ##[debug]matchOptions.noext: 'false'
2019-10-03T08:29:29.5705992Z ##[debug]matchOptions.nocase: 'true'
2019-10-03T08:29:29.5706333Z ##[debug]matchOptions.nonull: 'false'
2019-10-03T08:29:29.5708470Z ##[debug]matchOptions.matchBase: 'false'
2019-10-03T08:29:29.5708720Z ##[debug]matchOptions.nocomment: 'false'
2019-10-03T08:29:29.5708937Z ##[debug]matchOptions.nonegate: 'false'
2019-10-03T08:29:29.5709149Z ##[debug]matchOptions.flipNegate: 'false'
2019-10-03T08:29:29.5709393Z ##[debug]pattern: '**/*.SetParameters.xml'
2019-10-03T08:29:29.5760825Z ##[debug]findPath: 'd:\a\r1\a'
2019-10-03T08:29:29.5760954Z ##[debug]statOnly: 'false'
2019-10-03T08:29:29.5764993Z ##[debug]findPath: 'd:\a\r1\a'
2019-10-03T08:29:29.5765147Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2019-10-03T08:29:29.5765352Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2019-10-03T08:29:29.5765808Z ##[debug]findOptions.followSymbolicLinks: 'true'
2019-10-03T08:29:29.5771900Z ##[debug]  d:\a\r1\a (directory)
2019-10-03T08:29:29.5781289Z ##[debug]  d:\a\r1\a\Customer Portal (directory)
2019-10-03T08:29:29.5787902Z ##[debug]  d:\a\r1\a\Customer Portal\drop (directory)
2019-10-03T08:29:29.5794755Z ##[debug]  d:\a\r1\a\Customer Portal\drop\CustomerPortal.Cms.deploy-readme.txt (file)
2019-10-03T08:29:29.5795368Z ##[debug]  d:\a\r1\a\Customer Portal\drop\CustomerPortal.Cms.deploy.cmd (file)
2019-10-03T08:29:29.5796765Z ##[debug]  d:\a\r1\a\Customer Portal\drop\CustomerPortal.Cms.SetParameters.xml (file)
2019-10-03T08:29:29.5797164Z ##[debug]  d:\a\r1\a\Customer Portal\drop\CustomerPortal.Cms.SourceManifest.xml (file)
2019-10-03T08:29:29.5798389Z ##[debug]  d:\a\r1\a\Customer Portal\drop\CustomerPortal.Cms.zip (file)
2019-10-03T08:29:29.5799503Z ##[debug]  d:\a\r1\a\Customer Portal\drop\Deployment (directory)
2019-10-03T08:29:29.5805671Z ##[debug]  d:\a\r1\a\Customer Portal\drop\Deployment\azuredeploy.acc.json (file)
2019-10-03T08:29:29.5806066Z ##[debug]  d:\a\r1\a\Customer Portal\drop\Deployment\azuredeploy.json (file)
2019-10-03T08:29:29.5807313Z ##[debug]  d:\a\r1\a\Customer Portal\drop\Deployment\azuredeploy.prod.json (file)
2019-10-03T08:29:29.5808205Z ##[debug]  d:\a\r1\a\Customer Portal\drop\Deployment\azuredeploy.test.json (file)
2019-10-03T08:29:29.5808520Z ##[debug]13 results
2019-10-03T08:29:29.5809067Z ##[debug]found 13 paths
2019-10-03T08:29:29.5809295Z ##[debug]applying include pattern
2019-10-03T08:29:29.5809564Z ##[debug]adjustedPattern: 'd:\a\r1\a\**/*.SetParameters.xml'
2019-10-03T08:29:29.5828917Z ##[debug]1 matches
2019-10-03T08:29:29.5836295Z ##[debug]1 final results
2019-10-03T08:29:29.5860497Z replacing tokens in: d:\a\r1\a\Customer Portal\drop\CustomerPortal.Cms.SetParameters.xml
2019-10-03T08:29:29.5878216Z ##[debug]using encoding: utf-8
2019-10-03T08:29:29.6063901Z ##[debug]Umbraco.Url=https://mysite.net
2019-10-03T08:29:29.6064108Z ##[debug]Umbraco.Url: https://mysite.net
2019-10-03T08:29:29.6064342Z ##[debug]Blob.CdnDomain=https://cdn.mysite.net
2019-10-03T08:29:29.6064736Z ##[debug]Blob.CdnDomain: https://cdn.mysite.net
2019-10-03T08:29:29.6151331Z ##[section]Finishing: Replace tokens in **/*.SetParameters.xml
```

**Comment by qetza** [comment] 2019-10-04 08:54
Hi @deMD,
I'll see if i can reproduce the issue and fix it.

**Comment by qetza** [comment] 2019-10-05 05:36
Hi @deMD,
I could not reproduce your issue and based on the logs you have provided the task has found the 2 tokens and replaced them with values from your variables (last 5 lines of logs).

Is the issue you see in the `CustomerPortal.Cms.SetParameters.xml` file or another file? If it's another file can you check the content of SetParameters.xml after the transformation and also check that you use this file after doing the replace?

**Comment by deMD** [comment] 2019-10-08 17:57
I see the issue only in the target files, the SetParameters file looked good (the file linked is the file that is generated). The issue seemed to come from the deployment method used by the Azure App Service Deploy task. If set explicitly to Web Deploy it does work. 
![image](https://user-images.githubusercontent.com/22070292/66420223-cefe0200-ea05-11e9-975f-b050e86c3a53.png)

**Comment by qetza** [comment] 2019-10-20 09:24
Hi @deMD,
Glad your issue is fixed. I'll close the issue but feel free to reopen if needed.

**Closed by qetza** 2019-10-20 09:24 UTC
