### ISSUE TITLE
PathTooLongException

### ISSUE THREAD

**Issue by RAFP1** [qetza/vsts-replacetokens-task#28] opened 2017-02-02 09:14 UTC
I am deploying a website and have created a task entering a rootDirectory, targetFiles, encoding=auto, writeBOM = true, failonmissing=true token prefix/suffix __ to tokenise the webconfig files.
I run it on a  windows server 2012 r2 standard version 6.2 build 9200 , with IIS version 8.5.9600.16384 and it works fine. When I try to run it on another windows server 2012 r2 standard version 6.2 build 9200 , with IIS version 8.5.9600.16384 it fails with "System.IO.PathTooLongException: The specified path, file name, or both are too long."  
What else should I be comparing between the two servers to try and identify the issue?

**Comment by qetza** [comment] 2017-02-03 07:35
Hi @RAFP1,
The issue seems to be on the file path size when the task is opening one of your target file. Windows has a restriction on path size to 260 characters max.

You should check the path of your files on both your servers and see if there is a difference; you should see the file paths in the logs.

Guillaume

**Comment by qetza** [comment] 2017-02-25 05:36
Hi @RAFP1, did you managed to resolve your issue? If it is resolved or no more relevant could you close it.

Thanks

**Comment by qetza** [comment] 2017-03-23 21:07
Closing the issue as i have not enough information to reproduce it. Feel free to reopen if needed.

**Closed by qetza** 2017-03-23 21:07 UTC
